feat: add report_statistics with tests
kozaka93/toRpEDA pull request #127
Opened 2023-06-14 00:37 UTC by malwina0

2023-06-14 00:38 UTC, malwina0 commented
wiem, że w ostatniej funkcji nie pojawiają się wykresy ale nie wiem dlaczego tak jest i do czwartku raczej nie będę już w stanie tego ustalić :((

2023-06-14 05:09 UTC, kozaka93 commented
W Rmarkdown jest problem z wyświetlaniem wykresów w pętli, dodanie print(wykres) powinno rozwiązać sytuację.

Najlepiej 
```
for(){ ...

p <- wykres
print(p)

}
```

2023-06-14 17:49 UTC, skonieczkak requested changes
Oceniałem wyłącznie kod przygotowujący raport + szkielet raportu w pliku .rmd po poprawkach zaproponowanych poniżej -> wynikają prawdopodobnie z niezauważenia, że coś się nie zapisało/ coś było zapisane jako zmienna globalna
Dodatkowo niżej zawarłem feature `get_descriptive_stat`, który chyba jest nieintuicyjny i albo powinien zostać obsłużony po stronie raportu albo  w funkcji


Czy ten kod realizuje cel autora?
Tak, przygotowany raport jest świetnie napisany. Opisy proste, ale dla danologa zrozumiałe.

Czy w kodzie są jakieś oczywiste błędy logiczne?
Nie, nie znalazłem (po moich proponowanych poprawkach)

Patrząc na wymagania, czy wszystkie przypadki są w pełni zaimplementowane?
W przypadku samego raportu tak. 

Czy kod jest zgodny z istniejącymi wytycznymi stylu?
Tak.

Czy są jakieś obszary, w których kod mógłby zostać poprawiony? (skrócić, przyspieszyć, itp.)
Sam zrobiłem wszystko by nie używać knitra, by nie importować dodatkowych bibliotek. Z drugiej strony jednak jest to pakiet, który służy do wyświetlania takich rzeczy w raportach. Kwestia sporna.  Na plus, że użyto knitr::kable nie library("knitr"). 

Czy jest to najlepszy sposób na osiągnięcie pożądanego rezultatu?
Oprócz kwestii spornej z poprzedniego punktu to zapewne tak. Raport, który tworzy się przy użyciu funkcji wygląda bardzo dobrze, konkurencyjnie wobec raportów EDA obecnych na rynku. 
Minusem jest brak wspólnego wyglądu wykresów, który z tego co wiem był ustalany. Szkoda, ale wina tu leży nie po stronie autra tego pull request. 

Czy kod obsługuje wszystkie przypadki brzegowe?
Tak? -> znak zapytania dotyczy funkcji get_descriptive_stat, której działanie nie zostało w pełni obsłużone -> niżej przykład

Czy testy jednostkowe były odpowiednie?
Tak, testy sprawdzały czy powstaje plik z raportem. Pokrycie 100% więc jest super. (Po zaproponowanych poprawkach)

Czy jest odpowiednia dokumentacja i komentarze?
Tak. Komentarzy brak, ale nie są potrzebne. Kod w R jest zrozumiały bez nich, za to raport sam w sobie wszystko tłumaczy.

Poprawki:
report_statistics.R:
```
#' Generate a report with statistics on the data that includes basic descriptive
#' statistics, a histogram and correlation matrix for quantitative variables,
#' and barplots for qualitative variables.
#'
#' @param df A data frame for which the report is to be generated.
#' @param variables Variables for which the report is to be generated.
#' @param output_filename The output file name.
#'
#' @return Report is saved as local file. It contains basic descriptive statistics,
#' a histogram and correlation matrix for quantitative variables, and barplots
#' for qualitative variables.
#' @export
#'
#' @examples
#' \dontrun{
#' report_statistics(iris, output_file = "iris_statistics_report.html")
#' }
#' library(toRpEDA)

report_statistics <-
  function(df,
           variables = NULL,
           output_file = NULL,
           output_dir = getwd()) {

    if (is.null(variables)){
      variables = colnames(df)
    }


    input_file_path <- system.file('rmd/report_statistics', 'report_statistics.Rmd', package = 'toRpEDA')

    rmarkdown::render(
      input         = input_file_path,
      output_format = "html_document",
      output_file   = output_file,
      output_dir    = output_dir,
      params        = list(
        df          = df,
        variables   = variables
      )
    )
  }
```

Plik .Rmd:
```
```{r barplots, echo=FALSE, results='asis', warning=FALSE}

categorical_df <- df %>% select_if(function(col) is.factor(col) | is.character(col))
categorical_df_names = colnames(categorical_df)
for (i in 1:(length(categorical_df_names))) {
  cat("Variable name: **", categorical_df_names[[i]], "**\n", sep="")
  p <- plot_bar_qual(df, categorical_df_names[[i]])
  print(p)
}
```
```

Funkcja get_descriptive_stat zwraca listy różnej długości w zależności czy są species czy nie
```
get_descriptive_stat(iris)
get_descriptive_stat(mtcars)
```
co wywala raport. Powinno być to obsłużone

2023-06-14 17:54 UTC, skonieczkak commented
review zacząłem wcześniej niż ostatni fix

2023-06-18 16:19 UTC, kozaka93 commented
@skonieczkak czy teraz jest już wszystko ok?

2023-06-18 17:49 UTC, skonieczkak approved these changes
Widzę tylko "typo". Zatwierdzam

2023-06-18 18:25 UTC, merged