Add function redundant_cols()
kozaka93/toRpEDA pull request #71
Opened 2023-05-02 15:58 UTC by szuvarska

Adds function redundant_cols(), its documentation and tests. This function suggests redundant columns.

2023-05-03 13:50 UTC, Fersoil commented
ogólnie to niestety nie działa wyrzucanie identycznych kolumn - jezeli dwie kolumny mają identyczne wartości, nic się nie dzieje

2023-05-03 17:19 UTC, szuvarska commented
> ogólnie to niestety nie działa wyrzucanie identycznych kolumn - jezeli dwie kolumny mają identyczne wartości, nic się nie dzieje

Poprawione

2023-05-10 09:54 UTC, Fersoil submitted a review, later dismissed
chyba okej 🥇

2023-05-11 15:48 UTC, Fersoil requested changes
code review dla marty


1. Raczej tak, funkcja na usuwa powtarzające się kolumny lub sugeruje zmiany kiedy trzeba. Moim zdaniem zachowanie funkcji z drugiego przykładu jest troche nieintuicyjne - bo wybierane są tylko te kolumny które są podane, a ja bym np. wolał dostać niezmienioną ramkę. Jakbym miał ochote to sam bym sobie wybrał kolumny z outputu - na pewno tak jest łatwiej niż później mergować z orginałem. 


Ale ogólnie pomysł z wyborem kolumn do działania funkcji fajny.

2. wygląda na to, że nie

3. brakuje przypadku w zakładce examples, który by faktycznie pokazywał działanie funkcji. Przydałoby się pokazanie, że usuwa lub informuje o duplikacie. Brakuje pokazania działania o skorelowanych kolumnach (?) to jest dosc ciekawe, ale nie wiem czy wymagane

4. ogólnie wydaje mi się, że mogłoby być troche więcej komentarzy - w miejscach gdzie jest  

5. moim zdaniem nieintuicyjne jest jedynie zwracanie character(0) jezeli brakuje powtarzających sie kolumn. Wydaje mi sie ze fajnie jakby byla jakas wiadomość o tym, ze nic nie usunięto. 

Przy usuwaniu skorelowanych kolumn - dodałbym treshold do usuwania kolumn - a jeżeli nie to jakoś zaznaczył jaki ten treshold jest

6. jestem tego pewien

7. na to wygląda

8. coverage 100% :)

9. jak dla mnie brakuje komentarzy wewnątrz kodu - tak mi sie wydaje ze mozna by bylo gdzies napisac


błędy:

```
columns = c("ziemniak","marchewka","pietruszka") 
df = data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(df) = columns
```
brakuje po prostu jednego ifa moim zdaniem



taki warning, nie wiem czy chcesz z nim coś robić
```
Using an external vector in selections was deprecated in tidyselect
1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(col)

  # Now:
  data %>% select(all_of(col))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning
was generated. 

```


Zauważyłem też ciekawe zachowanie, związane z tym usuwaniem skorelowanych kolumn i nie do końca wiem jak należałoby to rozwiązać - 

```
> df <- iris
> df$col1 <- df$Sepal.Length + rnorm(length(df$Sepal.Length), 0, 0.3)
> df$col2 <- df$Sepal.Length + rnorm(length(df$Sepal.Length), 0, 1)
> cor(df$col1, df$Sepal.Length)
[1] 0.9455785
> cor(df$col2, df$Sepal.Length)
[1] 0.6315036

```
tutaj ciekawa sprawa, ze ten col2 jest wywalany, mimo ze chyba nie powinien być (bo treshold to 0.9)

nie wiem dokładnie jak to naprawić, ale coś jest nie tak bo ten col2 nie jest skorelowany aż tak - nie ma go w zmiennej highly_correlated przy wywołaniu kodu



A OK już rozumiem

col1 i col2 są wywalane ponieważ są bardzo podobne, juz na etapie wywalania takich samych kolumn - nie wiem czy chcemy takie zachowanie?

Ogólnie też przez to, że do usuwania podobnych kolumn usuwamy

2023-05-11 15:48 UTC, Fersoil commented on DESCRIPTION
> +  dplyr
jeszcze stats

2023-05-11 15:48 UTC, Fersoil commented on R/redundant_cols.R
> +      df <- select(df, -col)
dplyr:: brakuje

2023-05-11 16:41 UTC, szuvarska commented on R/redundant_cols.R
> +#' redundant_cols(iris, c("Sepal.Length","Sepal.Width","Species"), delete = TRUE)
Dlaczego?

2023-05-11 17:52 UTC, szuvarska commented
Przy błędzie z warzywami chodzi o to, że zwraca wszystkie kolumny?

2023-05-11 17:54 UTC, szuvarska commented
Przy wywalaniu kolumn col1 i col2 w iris nie chodzi o to, że są podobne, tylko mają unikalne wartości dla wszystkich wierszy, więc są traktowane jak ID. Mam zdefiniować ID inaczej? Mogę zrobić wyjątek dla liczb zmiennoprzecinkowych.

2023-05-11 20:56 UTC, Fersoil commented on R/redundant_cols.R
> +#' redundant_cols(iris, c("Sepal.Length","Sepal.Width","Species"), delete = TRUE)
znaczy bardziej chodzi o to, że nic się nie dzieje tak naprawdę

2023-05-11 20:59 UTC, Fersoil commented
wydaje mi sie ze z tymi zmiennoprzecinkowymi to mogłoby być całkiem okej podejście żeby nie usuwać takich kolumn, ewentualnie np. ostrzegać o tym lub dawać wybór, czy usuwamy lub nie

2023-05-11 23:18 UTC, szuvarska commented
> wydaje mi sie ze z tymi zmiennoprzecinkowymi to mogłoby być całkiem okej podejście żeby nie usuwać takich kolumn, ewentualnie np. ostrzegać o tym lub dawać wybór, czy usuwamy lub nie

Okej, zmieniłam warunek w ifie, żeby nie traktowało zmiennoprzecinkowych jako ID.

2023-05-13 17:29 UTC, Fersoil approved these changes

2023-05-13 17:30 UTC, Fersoil commented
luks
dobra robota pani Marto 👍 👍 👍

2023-05-14 19:03 UTC, merged