A21: Drzewo decyzyjne
kozaka93/toRpEDA pull request #72
Opened 2023-05-10 19:45 UTC by Fersoil

Pierwsza wersja funkcji, która przygotowuje prosty model drzewa decyzyjnego za pomocą biblioteki rpart i prezentuje podstawowe miary jakości dopasowania.

2023-05-11 15:46 UTC, szuvarska requested changes
1. Czy ten kod realizuje cel autora?
Tak.
2. Czy w kodzie są jakieś oczywiste błędy logiczne?
Nie ma.
3. Patrząc na wymagania, czy wszystkie przypadki są w pełni zaimplementowane?
Tak.
4. Czy kod jest zgodny z istniejącymi wytycznymi stylu?
Tak.
5. Czy są jakieś obszary, w których kod mógłby zostać poprawiony? (skrócić, przyspieszyć, itp.)
Nie wydaje mi się.
6. Czy jest to najlepszy sposób na osiągnięcie pożądanego rezultatu?
Myślę, że tak.
7. Czy kod obsługuje wszystkie przypadki brzegowe?
Myślę, że tak.
8. Czy testy jednostkowe były odpowiednie?
Jak najbardziej.
9. Czy jest odpowiednia dokumentacja i komentarze?
W większości. Brakuje returna w dokumentacji.

2023-05-11 15:46 UTC, szuvarska commented on tests/testthat/test-decision_tree.R
> +  expect_error(decision_tree(iris, target = "Species"))
Nie ma erroru.

2023-05-11 15:46 UTC, szuvarska commented on tests/testthat/test-decision_tree.R
> +  expect_equal(decision_tree(iris)$r_squared, 0.8507463, tolerance = 0.001)
Nie jest równe.

2023-05-11 15:46 UTC, szuvarska commented on R/decision_tree.R
> +    target = tail(colnames(df), n=1)
Funkcja tail nie jest z bazowego R, tylko z pakietu utils, więc powinna być wywoływana jako utils::tail(). Poza tym, czy w ogóle trzeba jej używać? Można się odwołać indeksem o numerze długości wektora. Wtedy nie będzie trzeba importować kolejnego pakietu.

2023-05-11 15:46 UTC, szuvarska commented on R/decision_tree.R
> +    y_pred <- predict(tree, test, type=pred_method)
Funkcja predict nie jest z bazowego R, tylko z biblioteki stats, więc powinna być wywoływana za pomocą stats::predict().

2023-05-11 15:46 UTC, szuvarska commented on R/decision_tree.R
> +  target_formula <- as.formula(paste(target_formula, "~ ."))
Funkcja as.formula nie jest z bazowego R, tylko z pakietu stats, więc powinna być wywoływana za pomocą stats::as.formula().

2023-05-11 18:22 UTC, szuvarska commented on R/decision_tree.R
> +    y_pred <- predict(tree, test, type=pred_method)
> tutaj nie jestem tego pewien, bo z tego co udało mi się znaleźć jest to predict.rpart, wiec nie wiem czy to jest na pewno bazowe/ze stats

Według funkcji check() używasz predict ze stats. Może chciałeś używać predict z pakietu rpart, ale zostało przykryte przez predict ze stats. W każdym razie musisz zaznaczyć, z którego pakietu ta funkcja jest, gdy jej używasz.

2023-05-11 21:45 UTC, szuvarska commented
W takim przypadku
```
col1 <- rnorm(100)
col2 <- rnorm(100)
decision_tree(data.frame(col1, col2))
``` 
radzi sobie średnio. Mamy message "y_pred contains classes not in y_true", co można by uwzględnić przy testach. Wychodzi drzewo, ale jest kompletnie nieczytelne. Balanced_accurancy jest inf. Może w tym wypadku nie pokazywać drzewa, tylko rzucić jakimś błędem po prostu?

2023-05-11 21:48 UTC, szuvarska commented
Można dodać testowanie błędu "unable to grow decision tree" np. ustawiając duże cp:
```
decision_tree(iris, cp = 10)
```

2023-05-11 22:28 UTC, szuvarska commented on R/decision_tree.R
>  #' decision_tree(iris, "Species")
Teraz ten przykład nie działa, skoro variables jest drugim argumentem.

2023-05-11 22:32 UTC, szuvarska commented
Wywala się, jak wszystkie wartości targetu są takie same, np. dla: 
```
decision_tree(head(iris, 25), target = "Species")
```

2023-05-13 17:24 UTC, Fersoil commented
> W takim przypadku
> 
> ```
> col1 <- rnorm(100)
> col2 <- rnorm(100)
> decision_tree(data.frame(col1, col2))
> ```
> 
> radzi sobie średnio. Mamy message "y_pred contains classes not in y_true", co można by uwzględnić przy testach. Wychodzi drzewo, ale jest kompletnie nieczytelne. Balanced_accurancy jest inf. Może w tym wypadku nie pokazywać drzewa, tylko rzucić jakimś błędem po prostu?


Dodałem błąd, w tym przypadku drzewo buduje się bardzo brzydko, bo stosujemy drzewo do klasyfikacji na problem regresji, dodałem ostrzeżenie

2023-05-14 18:32 UTC, szuvarska approved these changes
Szkoda, że nie ma testu do błędu "unable to grow decision tree", ale i tak coverage 98.96% całkiem ładnie.

2023-05-14 18:32 UTC, szuvarska commented on R/decision_tree.R
> +  if(!is.numeric(cp) | cp > 0)
Jak ostatnio sprawdzałam, to większe od zera były właśnie dodatnie liczby.

2023-05-15 15:14 UTC, Fersoil commented
super współpraca z reviewerem. 
zrobiliśmy fajny pakiet

2023-05-15 15:14 UTC, merged

2023-05-15 15:28 UTC, Fersoil commented on tests/testthat/test-decision_tree.R
>                                                     "boil carrots, parlsey and celery, you can use boiled vegetables for broth",
na sałatke jarzynową